networks:
  default:
    name: keycloak
    driver: overlay
    attachable: true

secrets:
  proxy.certificate:
    file: ${PROXY_CERT_PATH}
  proxy.key:
    file: ${PROXY_KEY_PATH}

services:
  proxy:
    image: traefik:v3.6
    ports:
      - target: 443
        published: 443
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == manager
    command: >
      --providers.swarm.endpoint=unix:///var/run/docker.sock
      --providers.swarm.exposedByDefault=false
      --providers.file.directory=/traefik
      --providers.file.watch=true
      --entryPoints.web.address=:80
      --entryPoints.websecure.address=:443
      --entryPoints.websecure.asDefault=true
      --entryPoints.web.http.redirections.entryPoint.to=websecure
      --entryPoints.web.http.redirections.entryPoint.scheme=https
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/traefik
    secrets:
      - source: proxy.certificate
        target: /certs/fullchain.pem
      - source: proxy.key
        target: /certs/privkey.pem
    ulimits:
      nofile:
        soft: 20000
        hard: 20000

  keycloak:
    image: skulpture/authnz:${TAG:-latest}
    hostname: keycloak.{{.Task.Slot}}
    environment:
      KC_CACHE: ispn
      KC_LOG_LEVEL: ${KC_LOG_LEVEL:-ERROR}
      KC_CACHE_STACK: kubernetes
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB_POOL_INITIAL_SIZE: ${KC_DB_POOL_INITIAL_SIZE:-1}
      KC_DB_POOL_MAX_SIZE: ${KC_DB_POOL_MAX_SIZE:-2}
      KC_DB_POOL_MIN_SIZE: ${KC_DB_POOL_MIN_SIZE:-0}
      KC_HOSTNAME: ${KC_HOSTNAME}
      # TODO: reconsider later
      KC_TRACING_SAMPLER_RATIO: 0.25
      KC_HTTP_ENABLED: "true"
      JAVA_OPTS_APPEND: "-Djgroups.dns.query=tasks.keycloak -Djgroups.bind_addr=match-address:10.0.2.*"
    command: >
      start 
      --optimized --http-enabled true --proxy-headers xforwarded
      --tracing-endpoint http://otel-collector:4317
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9000/health/ready || test $$? -eq 8 || exit 1" ]
      interval: 1m30s
      timeout: 1m
      retries: 5
      start_period: 1m
    deploy:
      mode: replicated
      replicas: 2
      labels:
        traefik.enable: "true"
        traefik.http.routers.authnz.rule: Host(`authnz.skulpture.xyz`)
        traefik.http.routers.authnz.tls.domains.main: skulpture.xyz
        traefik.http.routers.authnz.tls.domains.sans: "*.skulpture.xyz"
        traefik.http.routers.authnz.middlewares: authnz-inflightreq-limit, authnz-service-limit
        traefik.http.services.authnz-service.loadbalancer.server.port: 8080
        traefik.http.services.authnz-service.loadbalancer.server.scheme: http
        traefik.http.services.authnz-service.loadbalancer.healthcheck.path: /health/ready
        traefik.http.services.authnz-service.loadbalancer.healthcheck.status: 200
        traefik.http.services.authnz-service.loadbalancer.healthcheck.port: 9000
        traefik.http.services.authnz-service.loadbalancer.sticky.cookie.secure: "true"
        traefik.http.services.authnz-service.loadbalancer.sticky.cookie.httpOnly: "true"
        traefik.http.services.authnz-service.loadbalancer.sticky.cookie.domain: authnz.skulpture.xyz
        traefik.http.middlewares.authnz-inflightreq-limit.inflightreq.amount: 100
        # Proxied by CloudFlare only before reaching the VM
        # Rate limiting from traefik happens before it proxies
        traefik.http.middlewares.authnz-inflightreq-limit.inflightreq.sourcecriterion.ipstrategy.depth: 1
        traefik.http.middlewares.authnz-service-limit.ratelimit.average: 100
        traefik.http.middlewares.authnz-service-limit.ratelimit.burst: 150
        # Proxied by CloudFlare only before reaching the VM
        # Rate limiting from traefik happens before it proxies
        traefik.http.middlewares.authnz-service-limit.ratelimit.sourcecriterion.ipstrategy.depth: 1   
        traefik.swarm.lbswarm: "false"

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel/collector-config.yml:/etc/otelcol-contrib/config.yaml
    deploy:
      mode: replicated
      replicas: 1
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      OTEL_EXPORTER_OTLP_AUTH_TOKEN: ${OTEL_EXPORTER_OTLP_AUTH_TOKEN}
