networks:
  default:
    name: pgbackweb
    driver: overlay
    attachable: true

volumes:
  filebeat-data:
  heartbeat-data:
  metricbeat-data:


secrets:
  proxy.certificate:
    file: ${PROXY_CERT_PATH}
  proxy.key:
    file: ${PROXY_KEY_PATH}

services:
  proxy:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - target: 443
        published: 443
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    secrets:
      - source: proxy.certificate
        target: /certs/fullchain.pem
      - source: proxy.key
        target: /certs/privkey.pem
    ulimits:
      nofile:
        soft: 20000
        hard: 20000
    depends_on:
      - pgbackweb

  pgbackweb:
    image: skulpture/pgbackweb:${TAG:-latest}
    restart: unless-stopped
    environment:
      PBW_ENCRYPTION_KEY: ${PBW_ENCRYPTION_KEY}
      PBW_POSTGRES_CONN_STRING: ${PBW_POSTGRES_CONN_STRING}
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8085 || test $$? -eq 8 || exit 1" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 1m
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
