http:
  services:
    parseable-service:
      loadBalancer:
        sticky:
          cookie:
            secure: true
            httpOnly: true
            domain: telemetry.skulpture.xyz

    bugsink-service:
      loadBalancer:
        sticky:
          cookie:
            secure: true
            httpOnly: true
            domain: telemetry.skulpture.xyz
