// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: 612b5ff6bdab8e43d3068268cefc2ca7bfeb2399031ab4c747e3468974204e81

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "chartreuse";

export const themeNames: ThemeName[] = ["chartreuse"];

export type KcEnvName = never;

export const kcEnvNames: KcEnvName[] = [];

export const kcEnvDefaults: Record<KcEnvName, string> = {};

type KcContext = import("./login/KcContext").KcContext;

declare global {
	interface Window {
		kcContext?: KcContext;
	}
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
	const { kcContext, fallback } = props;
	return (
		<Suspense fallback={fallback}>
			{(() => {
				switch (kcContext.themeType) {
					case "login":
						return <KcLoginPage kcContext={kcContext} />;
				}
			})()}
		</Suspense>
	);
}
