// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: 71a4fde6ace748b5fc02fc4b5d7090a416092f7567a3abb57f1e64c0b42e1ae5

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "chartreuse";

export const themeNames: ThemeName[] = ["chartreuse"];

export type KcEnvName = never;

export const kcEnvNames: KcEnvName[] = [];

export const kcEnvDefaults: Record<KcEnvName, string> = {};

export type KcContext = import("./login/KcContext").KcContext;

declare global {
	interface Window {
		kcContext?: KcContext;
	}
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
	const { kcContext, fallback } = props;
	return (
		<Suspense fallback={fallback}>
			{(() => {
				switch (kcContext.themeType) {
					case "login":
						return <KcLoginPage kcContext={kcContext} />;
					case "account":
						<KcAccountThemePage kcContext={window.kcContext} />;
				}
			})()}
		</Suspense>
	);
}
